
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oaaejpvusmrwbivtyqps.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9hYWVqcHZ1c21yd2JpdnR5cXBzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI4Mjg3NDQsImV4cCI6MjA1ODQwNDc0NH0.RAuo6FOxCUGaCJmKXDV9jZecJekX6EoNPRx3toBxxnQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
